services:
  - type: web
    name: stock-line-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: FINMIND_TOKEN
        sync: false
      - key: ADMIN_TOKEN
        sync: false
